[package]
name = "coreos-metadata"
repository = "https://github.com/coreos/coreos-metadata"
license = "Apache-2.0"
authors = [ "Stephen Demos <stephen.demos@coreos.com>",
            "Luca Bruno <lucab@debian.org>" ]
description = "A simple cloud-provider metadata agent"
version = "3.0.1-alpha.0"

[[bin]]
name = "coreos-metadata"
path = "src/main.rs"

[profile.release]
lto = true

[dependencies]
clap = "2.26"
users = "0.7"
slog-term = "2.2"
slog-async = "2.1"
slog-scope = "4.0"
mime = "0.3"
serde = "1.0"
serde_derive = "1.0"
serde-xml-rs = "0.2"
serde_json = "1.0"
openssl = "0.9.17"
base64 = "0.9"
byteorder = "1.1"
pnet = "0.21"
reqwest = "0.7"
hyper = "0.11"
error-chain = { version = "0.12", default-features = false }
openssh-keys = "0.3"
update-ssh-keys = "0.3.0"
ipnetwork = "0.12"
hostname = "0.1"
tempdir = "0.3"
nix = "0.9"

[dependencies.slog]
version = "2.0"
features = ["max_level_trace", "release_max_level_info"]

[dev-dependencies]
mockito = "0.9"

[package.metadata.release]
sign-commit = true
upload-doc = false
disable-push = true
disable-publish = true
pre-release-commit-message = "cargo: coreos-metadata release {{version}}"
pro-release-commit-message = "cargo: version bump to {{version}}"
tag-message = "coreos-metadata v{{version}}"
tag-prefix = "v"
